/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		ApartmentSelect: typeof import('./src/components/ApartmentSelect/src/ApartmentSelect.vue')['default'];
		ApartmentSelectMultiple: typeof import('./src/components/ApartmentSelectMultiple/src/ApartmentSelectMultiple.vue')['default'];
		ApprovalProcess: typeof import('./src/components/SelectApprove/src/approvalProcess.vue')['default'];
		Backtop: typeof import('./src/components/Backtop/src/Backtop.vue')['default'];
		BankArea: typeof import('./src/components/SelectBankArea/src/BankArea.vue')['default'];
		BankBranch: typeof import('./src/components/BankBranch/src/BankBranch.vue')['default'];
		Calendar: typeof import('./src/components/Calendar/index.vue')['default'];
		Cell: typeof import('./src/components/Cell/src/Cell.vue')['default'];
		ConfigGlobal: typeof import('./src/components/ConfigGlobal/src/ConfigGlobal.vue')['default'];
		ContentDetailWrap: typeof import('./src/components/ContentDetailWrap/src/ContentDetailWrap.vue')['default'];
		ContentWrap: typeof import('./src/components/ContentWrap/src/ContentWrap.vue')['default'];
		ContractBlank: typeof import('./src/components/ContranctBlank/src/ContractBlank.vue')['default'];
		CopperModal: typeof import('./src/components/Cropper/src/CopperModal.vue')['default'];
		CountTo: typeof import('./src/components/CountTo/src/CountTo.vue')['default'];
		Crontab: typeof import('./src/components/Crontab/src/Crontab.vue')['default'];
		Cropper: typeof import('./src/components/Cropper/src/Cropper.vue')['default'];
		CropperAvatar: typeof import('./src/components/Cropper/src/CropperAvatar.vue')['default'];
		CustomSource: typeof import('./src/components/SelectCustomSource/src/CustomSource.vue')['default'];
		Descriptions: typeof import('./src/components/Descriptions/src/Descriptions.vue')['default'];
		DeviceListInfo: typeof import('./src/components/DeviceListInfo/src/DeviceListInfo.vue')['default'];
		Dialog: typeof import('./src/components/Dialog/src/Dialog.vue')['default'];
		DictTag: typeof import('./src/components/DictTag/src/DictTag.vue')['default'];
		District: typeof import('./src/components/DISTRICT/src/district.vue')['default'];
		DocAlert: typeof import('./src/components/DocAlert/index.vue')['default'];
		Echart: typeof import('./src/components/Echart/src/Echart.vue')['default'];
		Editor: typeof import('./src/components/Editor/src/Editor.vue')['default'];
		Education: typeof import('./src/components/SelectEducation/src/education.vue')['default'];
		ElementBaseInfo: typeof import('./src/components/bpmnProcessDesigner/package/penal/base/ElementBaseInfo.vue')['default'];
		ElementForm: typeof import('./src/components/bpmnProcessDesigner/package/penal/form/ElementForm.vue')['default'];
		ElementListeners: typeof import('./src/components/bpmnProcessDesigner/package/penal/listeners/ElementListeners.vue')['default'];
		ElementMultiInstance: typeof import('./src/components/bpmnProcessDesigner/package/penal/multi-instance/ElementMultiInstance.vue')['default'];
		ElementOtherConfig: typeof import('./src/components/bpmnProcessDesigner/package/penal/other/ElementOtherConfig.vue')['default'];
		ElementProperties: typeof import('./src/components/bpmnProcessDesigner/package/penal/properties/ElementProperties.vue')['default'];
		ElementTask: typeof import('./src/components/bpmnProcessDesigner/package/penal/task/ElementTask.vue')['default'];
		Error: typeof import('./src/components/Error/src/Error.vue')['default'];
		FlowCondition: typeof import('./src/components/bpmnProcessDesigner/package/penal/flow-condition/FlowCondition.vue')['default'];
		Form: typeof import('./src/components/Form/src/Form.vue')['default'];
		Highlight: typeof import('./src/components/Highlight/src/Highlight.vue')['default'];
		Icon: typeof import('./src/components/Icon/src/Icon.vue')['default'];
		IconSelect: typeof import('./src/components/Icon/src/IconSelect.vue')['default'];
		IFrame: typeof import('./src/components/IFrame/src/IFrame.vue')['default'];
		ImageViewer: typeof import('./src/components/ImageViewer/src/ImageViewer.vue')['default'];
		Infotip: typeof import('./src/components/Infotip/src/Infotip.vue')['default'];
		InputPassword: typeof import('./src/components/InputPassword/src/InputPassword.vue')['default'];
		MyScroll: typeof import('./src/components/Scroll/src/MyScroll.vue')['default'];
		MyUpload: typeof import('./src/components/MyUpload/src/MyUpload.vue')['default'];
		Pagination: typeof import('./src/components/Pagination/index.vue')['default'];
		Particles: typeof import('./src/components/particles/index.vue')['default'];
		PdfPreview: typeof import('./src/components/PdfPreview/src/PdfPreview.vue')['default'];
		PdfPreviewDialog: typeof import('./src/components/PdfPreview/src/PdfPreviewDialog.vue')['default'];
		ProcessDesigner: typeof import('./src/components/bpmnProcessDesigner/package/designer/ProcessDesigner.vue')['default'];
		ProcessPalette: typeof import('./src/components/bpmnProcessDesigner/package/palette/ProcessPalette.vue')['default'];
		ProcessViewer: typeof import('./src/components/bpmnProcessDesigner/package/designer/ProcessViewer.vue')['default'];
		PropertiesPanel: typeof import('./src/components/bpmnProcessDesigner/package/penal/PropertiesPanel.vue')['default'];
		ReceiveTask: typeof import('./src/components/bpmnProcessDesigner/package/penal/task/task-components/ReceiveTask.vue')['default'];
		RoomInfoTitle: typeof import('./src/components/RoomInfoTitle/src/RoomInfoTitle.vue')['default'];
		RoomProperty: typeof import('./src/components/RoomProperty/src/roomProperty.vue')['default'];
		RoomsCascader: typeof import('./src/components/RoomsCascader/src/RoomsCascader.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
		ScriptTask: typeof import('./src/components/bpmnProcessDesigner/package/penal/task/task-components/ScriptTask.vue')['default'];
		Search: typeof import('./src/components/Search/src/Search.vue')['default'];
		Selectbank: typeof import('./src/components/SelectBank/src/selectbank.vue')['default'];
		SelectCardType: typeof import('./src/components/SelectCardtype/src/select-card-type.vue')['default'];
		SelectEmployee: typeof import('./src/components/SelectEmployee/src/SelectEmployee.vue')['default'];
		SelectEntrustedFloowStatus: typeof import('./src/components/SelectEntrustedFollowStatus/src/SelectEntrustedFloowStatus.vue')['default'];
		SelectGender: typeof import('./src/components/SelectGender/src/SelectGender.vue')['default'];
		SelectIndividualTradeType: typeof import('./src/components/SelectIndividualTradeType/src/SelectIndividualTradeType.vue')['default'];
		SelectModelCategory: typeof import('./src/components/SelectModelCategory/src/SelectModelCategory.vue')['default'];
		SelectPreferenceHouseType: typeof import('./src/components/SelectPerfereneceHouseType/src/SelectPreferenceHouseType.vue')['default'];
		Selectstaff: typeof import('./src/components/SelectStaff/src/selectstaff.vue')['default'];
		SignalAndMessage: typeof import('./src/components/bpmnProcessDesigner/package/penal/signal-message/SignalAndMessage.vue')['default'];
		Sticky: typeof import('./src/components/Sticky/src/Sticky.vue')['default'];
		Table: typeof import('./src/components/Table/src/Table.vue')['default'];
		Tooltip: typeof import('./src/components/Tooltip/src/Tooltip.vue')['default'];
		UploadFile: typeof import('./src/components/UploadFile/src/UploadFile.vue')['default'];
		UploadImg: typeof import('./src/components/UploadFile/src/UploadImg.vue')['default'];
		UploadImgAndFile: typeof import('./src/components/UploadFile/src/UploadImgAndFile.vue')['default'];
		UploadImgs: typeof import('./src/components/UploadFile/src/UploadImgs.vue')['default'];
		UploadVideo: typeof import('./src/components/UploadFile/src/UploadVideo.vue')['default'];
		UserTask: typeof import('./src/components/bpmnProcessDesigner/package/penal/task/task-components/UserTask.vue')['default'];
		UserTaskListeners: typeof import('./src/components/bpmnProcessDesigner/package/penal/listeners/UserTaskListeners.vue')['default'];
		Verify: typeof import('./src/components/Verifition/src/Verify.vue')['default'];
		VerifyPoints: typeof import('./src/components/Verifition/src/Verify/VerifyPoints.vue')['default'];
		VerifySlide: typeof import('./src/components/Verifition/src/Verify/VerifySlide.vue')['default'];
		XButton: typeof import('./src/components/XButton/src/XButton.vue')['default'];
		XTextButton: typeof import('./src/components/XButton/src/XTextButton.vue')['default'];
	}
}
